# Generated by Django 2.1.4 on 2019-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=64)),
                ('asset_type', models.CharField(max_length=64)),
                ('asset_class', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_detail_name', models.CharField(max_length=128)),
                ('asset_detail_value', models.CharField(max_length=256)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetailMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=64)),
                ('asset_detail_name', models.CharField(max_length=128)),
                ('asset_detail_type', models.CharField(max_length=128)),
            ],
        ),
    ]
